import { NgModule, Component, Input } from '@angular/core';
import { Chart } from './component';
import { LiteChart } from './LiteChart';
import { Axis, Coord, Facet, Guide, Legend, Tooltip } from './subChart/';
import { Series, Pie, Sector, Line, SmoothLine, DashLine, Area, StackArea, SmoothArea,
  Bar, StackBar, DodgeBar, Point, Waterfall, Funnel, Pyramid, RadialBar, Schema,
  Box, Candle, Polygon, Contour, Heatmap, Edge, Sankey } from './subChart/Series';
import { View, FacetView } from './subChart/View';

@NgModule({
  declarations: [
    Axis,
    Coord,
    Facet,
    Guide,
    Legend,
    Series,
    Tooltip,
    View,
    Chart,
    FacetView,
    LiteChart,
    Pie,
    Sector,
    Line,
    SmoothLine,
    DashLine,
    Area,
    StackArea,
    SmoothArea,
    Bar,
    StackBar,
    DodgeBar,
    Point,
    Waterfall,
    Funnel,
    Pyramid,
    RadialBar,
    Schema,
    Box,
    Candle,
    Polygon,
    Contour,
    Heatmap,
    Edge,
    Sankey,
  ],
  exports: [
    Axis,
    Coord,
    Facet,
    Guide,
    Legend,
    Series,
    Tooltip,
    View,
    Chart,
    Polygon,
    FacetView,
    LiteChart,
    Pie,
    Sector,
    Line,
    SmoothLine,
    DashLine,
    Area,
    StackArea,
    SmoothArea,
    Bar,
    StackBar,
    DodgeBar,
    Point,
    Waterfall,
    Funnel,
    Pyramid,
    RadialBar,
    Schema,
    Box,
    Candle,
    Polygon,
    Contour,
    Heatmap,
    Edge,
    Sankey,
  ]
})
export class ViserModule {
}
